Introcução

- Abordagem robabilística (teorema de bayes)
- Exemplos
    - Filtros de spam
    - Mineração de emoções em uma frase
    - Separação de documentos
    
 Correção laplaciana serve para corrigir o problema da multiplicação por zero, geralmente em pequenas bases de dados onde as probabilidades são zeradas. Assim ele adiciona um registro de correção

# Algoritmo de Naïve Bayes


### Vantagens
- Rápido
- Fácil Interpretação
- Trabalha com altas dimensões
- Boas previsões em bases pequenas

### Desvantagens
- Combinação de Características (atributos independentes) - cada par de características são independentes (Nem sempre é verdade).
 

In [4]:
import pandas as pd
import seaborn as sns
import plotly.express as px
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv('risco_credito.csv')

In [3]:
df

historia divida garantias     renda     risco
0           ruim   alta   nenhuma      0_15      alto
1   desconhecida   alta   nenhuma     15_35      alto
2   desconhecida  baixa   nenhuma     15_35  moderado
3   desconhecida  baixa   nenhuma  acima_35      alto
4   desconhecida  baixa   nenhuma  acima_35     baixo
5   desconhecida  baixa  adequada  acima_35     baixo
6           ruim  baixa   nenhuma      0_15      alto
7           ruim  baixa  adequada  acima_35  moderado
8            boa  baixa   nenhuma  acima_35     baixo
9            boa   alta  adequada  acima_35     baixo
10           boa   alta   nenhuma      0_15      alto
11           boa   alta   nenhuma     15_35  moderado
12           boa   alta   nenhuma  acima_35     baixo
13          ruim   alta   nenhuma     15_35      alto

# Divisão das bases de treinamento e teste

In [5]:
x_df = df.iloc[:,0:4].values

In [8]:
y_df = df.iloc[:,4].values

In [9]:
x_df[0], y_df[0]

(array(['ruim', 'alta', 'nenhuma', '0_15'], dtype=object), 'alto')

In [11]:
from sklearn.preprocessing import LabelEncoder

label_encoder_historia = LabelEncoder()
label_encoder_divida = LabelEncoder()
label_encoder_garantias = LabelEncoder()
label_encoder_renda = LabelEncoder()

In [12]:
x_df[:,0] = label_encoder_historia.fit_transform(x_df[:,0])
x_df[:,1] = label_encoder_divida.fit_transform(x_df[:,1])
x_df[:,2] = label_encoder_garantias.fit_transform(x_df[:,2])
x_df[:,3] = label_encoder_renda.fit_transform(x_df[:,3])

In [14]:
# por conta de ser uma base de dados pequena, nao utiliaremos onehotencoding. nao e necessario pois iria aumentar muito o numero de colunas

x_df

array([[2, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 1, 0, 2],
       [2, 1, 1, 0],
       [2, 1, 0, 2],
       [0, 1, 1, 2],
       [0, 0, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 2],
       [2, 0, 1, 1]], dtype=object)

In [15]:
import pickle
with open('risco_credito.pkl','wb') as f:
    pickle.dump([x_df,y_df], f)

**Utilizando o alogirtmo naive bayes:**

In [16]:
from sklearn.naive_bayes import GaussianNB

In [17]:
naive_dados = GaussianNB()
naive_dados.fit(x_df, y_df)

GaussianNB()

In [18]:
#historia boa (0), divida alta (0), garantias nenhuma (1), renda > 35 (2) -> [0,0,1,2]
#historia ruim (2), divida alta (0), garantias adequada (0), renda <15 (0) -> [2,0,0,0]

previsao = naive_dados.predict([[0,0,1,2], [2,0,0,0]])

In [19]:
previsao

array(['baixo', 'moderado'], dtype='<U8')

In [21]:
naive_dados.classes_

array(['alto', 'baixo', 'moderado'], dtype='<U8')

In [22]:
naive_dados.class_count_

array([6., 5., 3.])

In [23]:
#42% da base de dados são registros 'alto', e assim por diante
naive_dados.class_prior_

array([0.42857143, 0.35714286, 0.21428571])