classificação -> prever uma classe (rótulos)
regressão -> prever um número

regressão logística é um método de classificação
    - utiliza a função sigmoide (S) para conseguir fazer a classificação dos registros 
    
Função sigmoide sempre retorna valores entre 0 e 1

Equação da reta: $ y = b_0 + b_1 * x$

Função sigmoide:$ p = \frac{1}{1+e^-y}$

e por fim, para fazer efetivamente a aplicação do algoritmo utilizamos a transformação logit sendo ela $log(\frac{p}{1-p}) = b_0 + b_1 * x $

- regresão logistica mais facil de ser utilizada quando a variavel resposta tem apenas 2 classes
- descida do gradiente para encontrar parametro com menor erro possível

# Base de dados risco credito

In [1]:
import pickle
with open('risco_credito.pkl','rb')as f:
    x_df, y_df = pickle.load(f)

In [2]:
x_df, y_df

(array([[2, 0, 1, 0],
        [1, 0, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 2],
        [1, 1, 1, 2],
        [1, 1, 0, 2],
        [2, 1, 1, 0],
        [2, 1, 0, 2],
        [0, 1, 1, 2],
        [0, 0, 0, 2],
        [0, 0, 1, 0],
        [0, 0, 1, 1],
        [0, 0, 1, 2],
        [2, 0, 1, 1]], dtype=object),
 array(['alto', 'alto', 'moderado', 'alto', 'baixo', 'baixo', 'alto',
        'moderado', 'baixo', 'baixo', 'alto', 'moderado', 'baixo', 'alto'],
       dtype=object))

In [3]:
import numpy as np
x_df = np.delete(x_df, [2,7,11], axis = 0) #axis = 0 exclui linhas e axis = 1 exclui coluna
y_df = np.delete(y_df, [2,7,11], axis = 0)

In [4]:
x_df, y_df

(array([[2, 0, 1, 0],
        [1, 0, 1, 1],
        [1, 1, 1, 2],
        [1, 1, 1, 2],
        [1, 1, 0, 2],
        [2, 1, 1, 0],
        [0, 1, 1, 2],
        [0, 0, 0, 2],
        [0, 0, 1, 0],
        [0, 0, 1, 2],
        [2, 0, 1, 1]], dtype=object),
 array(['alto', 'alto', 'alto', 'baixo', 'baixo', 'alto', 'baixo', 'baixo',
        'alto', 'baixo', 'alto'], dtype=object))

In [5]:
from sklearn.linear_model import LogisticRegression

In [6]:
reg = LogisticRegression(random_state = 1)
reg.fit(x_df,y_df)

LogisticRegression(random_state=1)

In [7]:
reg.intercept_   #equivale ao b_0

array([-0.80828993])

In [8]:
reg.coef_ #coeficientes b1, b2, be e b4

array([[-0.76704533,  0.23906678, -0.47976059,  1.12186218]])

In [9]:
#historia boa (0), divida alta (0), garantias nenhuma (1), renda > 35 (2) -> [0,0,1,2]
#historia ruim (2), divida alta (0), garantias adequada (0), renda <15 (0) -> [2,0,0,0]
previsor1 = reg.predict([[0,0,1,2], [2,0,0,0]])
previsor1

array(['baixo', 'alto'], dtype=object)

# Base Credit data

In [10]:
import pickle
with open('credit.pkl','rb')as f:
    x_df_train, y_df_train, x_df_test, y_df_test = pickle.load(f)

In [11]:
regressao = LogisticRegression(random_state = 1)
regressao.fit(x_df_train, y_df_train)

LogisticRegression(random_state=1)

In [12]:
regressao.intercept_ 

array([-6.02975455])

In [13]:
regressao.coef_

array([[-2.5492665 , -3.72279323,  3.93940035]])

In [14]:
# 0 - pessoa paga 
# 1 - pessoa nao paga
previsor = regressao.predict(x_df_test)
previsor

array([1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [16]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy_score(y_df_test, previsor)

0.946

In [17]:
confusion_matrix(y_df_test, previsor)

array([[423,  13],
       [ 14,  50]], dtype=int64)

In [18]:
print(classification_report(y_df_test, previsor))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97       436
           1       0.79      0.78      0.79        64

    accuracy                           0.95       500
   macro avg       0.88      0.88      0.88       500
weighted avg       0.95      0.95      0.95       500



# Base Census

In [19]:
with open('census.pkl', 'rb') as f:
    x_df_train, y_df_train, x_df_test, y_df_test = pickle.load(f)

In [20]:
regressao = LogisticRegression(random_state = 1)
regressao.fit(x_df_train, y_df_train)

LogisticRegression(random_state=1)

In [25]:
previsor = regressao.predict(x_df_test)
previsor

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      dtype=object)

In [22]:
accuracy_score(y_df_test, previsor)

0.849539406345957

In [23]:
confusion_matrix(y_df_test, previsor)

array([[3423,  270],
       [ 465,  727]], dtype=int64)

In [24]:
print(classification_report(y_df_test, previsor))

              precision    recall  f1-score   support

       <=50K       0.88      0.93      0.90      3693
        >50K       0.73      0.61      0.66      1192

    accuracy                           0.85      4885
   macro avg       0.80      0.77      0.78      4885
weighted avg       0.84      0.85      0.84      4885

